### ISSUE TITLE
Test with armbian on cubietruck 

### ISSUE THREAD

**Issue by MariusRumpf** [hypriot/cluster-lab#11]
Based on fresh jessie armbian installation and following the [blog guide](http://blog.hypriot.com/post/family_arm_hardware_for_docker_more_children/) as a base.

Installed `docker-compose` from dpkg directly, since the following did __not__ provide the package, only the `docker-hypriot` package.
```bash
curl -s https://packagecloud.io/install/repositories/Hypriot/Schatzkiste/script.deb.sh | sudo bash
```

Armbian does use init instead of systemd by default, which leads to:
```bash
$ sudo systemctl start cluster-start
Failed to get D-Bus connection: Unknown error -1
```
Found the following solution to change to systemd http://forum.armbian.com/index.php/topic/342-dbus-error-when-using-systemctl/

Latest not so easy solved problem is that the kernel does not support vxlan, which leads to not working overlay networks. In order to make this work the kernel has to be recompiled with the option `-> Device Drivers -> Network device support -> Network core driver support -> Virtual eXtensible Local Area Network (VXLAN) [m]`.

**Comment by MathiasRenner** [comment]
@MariusRumpf: We will soon have a FAQ, which will also cover of how to use our "Schatzkiste" properly. This would have made your day easier. Sorry for now!
We recommend to copy & paste this into the terminal:

```
sudo apt-get update
sudo apt-get install -y apt-transport-https
echo "deb https://packagecloud.io/Hypriot/Schatzkiste/debian/ wheezy main" | sudo tee /etc/aptsources.list.d/hypriot.list
sudo apt-get update
```

Then, install any of the available packages, such as *docker-compose* like this:
`sudo apt-get install -y docker-compose`

---

Thanks for your pointer to the VXLAN kernel option! Do you think you could prepare a small PR that includes your hint in the README.md's **troubleshooting** section?

**Comment by MariusRumpf** [comment]
@MathiasRenner There is a typo in your example sudo tee /etc/apt __/__ sources.list.d/hypriot.list
But I checked it again now and that works perfect. 

Reported the VXLAN kernel option and it has been merged already, so that should be in the next release of armbian kernel. https://github.com/igorpecovnik/lib/issues/134

I will see that I find my complete problem again to show it in the README. I cannot provide a complete tutorial but some resources on how to fix it.

**Comment by DieterReuter** [comment]
@MariusRumpf in order to check all the kernel settings that are important for running Docker, you should use this script from the Docker repo: https://github.com/docker/docker/blob/master/contrib/check-config.sh. Can you run it on your board and provide the output log, then we can check if there are any other important kernel settings still missing.

**Comment by MathiasRenner** [comment]
@MariusRumpf: Good to hear that it works for you. I updated the command, thanks!
And good to see that Igor handled it in Armbian! :+1: +1

**Comment by MariusRumpf** [comment]
@DieterReuter The check does not provide any notice on the VXLAN kernel flag as far as I noticed.
https://gist.github.com/MariusRumpf/dee22640175d28267558 (with VXLAN enabled in kernel)
The check you posted previosly in your blog does seem to have the same output as I can tell.
https://gist.github.com/hypriot/5d1236bb9c63f7ef7be8 (this had VXLAN disabled in kernel)

**Comment by DieterReuter** [comment]
You're right, they only check the `VETH` setting. But these kernel settings are quite OK, maybe some of the optional features could be activated too. Then the kernel would be really perfect for running Docker.

**Comment by MariusRumpf** [comment]
@DieterReuter Or maybe you extend the script to check that flag too. Like so https://gist.github.com/MariusRumpf/7a0858b5fadb68adbd75 (Haven't tested it in a not enabled state)

**Comment by MariusRumpf** [comment]
New armbian version was released yesterday which includes all needed kernel changes (v5.0.0). So getting up and running is only a matter installing the hypriot schatzkiste.
