### ISSUE TITLE
Configuration for docker daemon

### ISSUE THREAD

**Issue by MariusRumpf** [hypriot/cluster-lab#12]
A configuration option for the docker daemon would be nice.

Let's say I want to run a local docker registry and use that with all my daemons. I would have to change the `/etc/default/docker` file to add `--insecure-registry myregistrydomain.com:5000` for every daemon in my cluster. Only possible way would be to change the `cluster-start.sh` file, since it will be overwritten otherwise.
Even better when I can supply this config with the flash tool, too. This makes it a very easy setup then.

**Comment by aetherical** [comment]
This shouldn't be difficult to add to the flash tool -- I've added features like this to it before. I'm at a conference this week and with any luck will be featuring the cluster-lab in a demo, but I'll get it done next week.
