### ISSUE TITLE
/etc/resolv.conf points to private name servers

### ISSUE THREAD

**Issue by aetherical** [hypriot/cluster-lab#15]
While running up a cluster-lab imaged pi to be a dhcp server, I noticed that the resolv.conf points to private nameservers in Germany.  

I know that the expected usecase is for the cluster-lab hosts to have dhcp provide them with their IP/name resolution data, but on the off chance that someone is either exploring (or a serious edge case like a travelling cloud-in-a-box), would it make sense to have it point by default to the google public nameservers (8.8.8.8 and 8.8.4.4)?

**Comment by MathiasRenner** [comment]
@aetherical The Cluster Lab does not change nameservers. Is it maybe the IP of your own router?

**Comment by aetherical** [comment]
On 2016-01-06 11:10, Mathias Renner wrote:
> @aetherical [1] The Cluster Lab does not change nameservers. Is it
> maybe the IP of your own router?
> 
> --
> Reply to this email directly or view it on GitHub [2].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/aetherical
> [2] 
> https://github.com/hypriot/cluster-lab/issues/15#issuecomment-169372364

When I mount the freshly flash'd image, /etc/resolv.conf has the 
following contents:

### Hetzner Online AG installimage
# nameserver config
nameserver 213.133.98.98
nameserver 213.133.99.99
nameserver 213.133.100.100

Then nslookup returns:

$ nslookup 213.133.98.98
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
98.98.133.213.in-addr.arpa	name = ns1-coloc.hetzner.de.

Authoritative answers can be found from:

I had written earlier BC (Before Coffee) and wasn't precisely clear.

Here's another test (admittedly from a conference, I can vpn into the 
house and paranoia check if people think there is value):

$ nslookup
> server 213.133.98.98
Default server: 213.133.98.98
Address: 213.133.98.98#53
> prep.ai.mit.edu
;; connection timed out; no servers could be reached
^C
$ nslookup
> server 8.8.8.8
Default server: 8.8.8.8
Address: 8.8.8.8#53
> prep.ai.mit.edu
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
prep.ai.mit.edu	canonical name = ftp.gnu.org.
Name:	ftp.gnu.org
Address: 208.118.235.20

Note above that the nameserver in the images /etc/resolv.conf is not 
reachable...

Matt

**Comment by firecyberice** [comment]
Thanks
I found the part in our SD image creation script.
It is a corner case. Normally the `/etc/resolv.conf` will be rewritten by connecting to a LAN with a DHCP server configured to deliver DNS servers.
But we will pay attention to this issue in the next releases of our images.

I close this issue but you can reopen it if needed.

**Comment by StefanScherer** [comment]
@firecyberice Do we need a test for this? :smile:
