### ISSUE TITLE
Add additional delay in startup sequence

### ISSUE THREAD

**Issue by whatever4711** [hypriot/cluster-lab#16]
Since **consul** takes some time to complete the startup process on the slave nodes, the **swarm** join functionality is not registering the current node in the key value store of consul.

An additional delay between starting up **consul** and **swarm join** should help to overcome this issue.

**Comment by MathiasRenner** [comment]
Thanks for the pointer! It seems like neither Docker-Compose nor Docker includes a sleep command to achieve this. So we maybe divide `cluster.yml` into single run commands with a `sleep` in between. 

What do you think? ping @whatever4711 @firecyberice

**Comment by firecyberice** [comment]
@MathiasRenner  That's the plan ;-)

**Comment by whatever4711** [comment]
Thanks to the new `docker-compose` in version 2, we do not need a sleep anymore. I would suggest to update the compose file, declare the `depends_on: consul` key for `swarm` and everything should work with Docker 1.10. Currently, I am testing it.
Moreover, there is no need for *two* seperate compose files or some _hacky_ shell scripts.
What do you think about an upgrade? @MathiasRenner @firecyberice

**Comment by MathiasRenner** [comment]
@whatever4711 I agree. Let's upgrade the docker-compose file and according scripts.

**Comment by MathiasRenner** [comment]
Solved as indicated by @firecyberice

**Comment by Govinda-Fichtner** [comment]
This is made obsolete by the recent refactoring.
