### ISSUE TITLE
Consul container not starting

### ISSUE THREAD

**Issue by rllola** [hypriot/cluster-lab#17]
When running the OS for the first time I can see that the docker container for consul is not starting:
```
$ docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS                         PORTS                    NAMES
3528081eb5dc        hypriot/rpi-swarm    "/swarm manage consul"   About a minute ago   Up About a minute              0.0.0.0:2378->2375/tcp   bin_swarmmanage_1
db3898d5fc5f        hypriot/rpi-consul   "/consul agent -serve"   About a minute ago   Restarting (1) 9 seconds ago                            bin_consul_1
7d9b0936d53e        hypriot/rpi-swarm    "/swarm join --advert"   About a minute ago   Up About a minute              2375/tcp                 bin_swarm_1
```
So i  did `docker logs bin_consul_1` to see what was happening :
```
==> Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.
==> WARNING: BootstrapExpect Mode is specified as 1; this is the same as Bootstrap mode.
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.
```

I'seen on the blog's comment that I am not the only one with this issue.

**Comment by Govinda-Fichtner** [comment]
@rllola Could you please check which version of Consul you are running on your cluster nodes?

Executing `docker run -ti --rm hypriot/rpi-consul --version` should output the version info.

**Comment by MariusRumpf** [comment]
@Govinda-Fichtner As reported in gitter chat, changing the `cluster-start` to include `rpi-consul:0.5.0` instead of `rpi-consul` resolves this error.

**Comment by Govinda-Fichtner** [comment]
OK. Well the problem is that we did not neither updated the Cluster Lab sd-card image nor the deb package. 

In https://github.com/hypriot/cluster-lab/blob/master/package/usr/local/bin/cluster-start.sh#L140 we already fixed it. Version 0.6.0 of Consul should work, too.

/cc @firecyberice @MathiasRenner Could that be? If yes, we need to update those soon to prevent further confusion.

**Comment by rllola** [comment]
Hi @Govinda-Fichtner 

```
$ docker run -ti --rm hypriot/rpi-consul --version
Consul v0.6.3
Consul Protocol: 3 (Understands back to: 1)
```

**Comment by rllola** [comment]
@MariusRumpf +1 Changing for 0.5.0 did fix it.

**Comment by Govinda-Fichtner** [comment]
@rllola Ok. As I expected.

To fix this change the following file on each node

`/usr/local/bin/cluster-start.sh`

similar to this

https://github.com/hypriot/cluster-lab/blob/master/package/usr/local/bin/cluster-start.sh#L140

Afterwards do a `cluster-stop.sh` followed by a `cluster-start.sh` on each node starting with the first one you switched on. Give the first enough time to completely run `cluster-start.sh` before you do the same on the other nodes.

This is just a workaround for you till we fixed the Cluster Lab sd card image and the debian image.

**Comment by MathiasRenner** [comment]
Thank you guys so much for your feedback!

The SD card image is now updated to consul 0.6.0 with an additional minor change such that it should work better now. At least for Govinda and me it's just fine now. 

Do you have a chance to test if this version works for you as well?
https://github.com/hypriot/cluster-lab/releases/

**Comment by rllola** [comment]
+1
I have tested the new release and it works fine ! Thank you.
You should also update your blog article so it use the new release.

New command line
```
$ flash --hostname cl-master https://github.com/hypriot/cluster-lab/releases/download/v0.1.1/hypriot-rpi-20160121-235123.img.zip
$ flash --hostname cl-node-1 https://github.com/hypriot/cluster-lab/releases/download/v0.1.1/hypriot-rpi-20160121-235123.img.zip
```

So in the future people won't have this issue.

**Comment by MathiasRenner** [comment]
@rllola Thank you for the feedback, awesome! The download link in the blog post is up to date now.

@MariusRumpf I moved the download of the SD card image to our blog post because this repo does not build the SD card image but only the DEB package. All links are updated, following them should be just fine.
