### ISSUE TITLE
Avahi (and avahi browse) delay

### ISSUE THREAD

**Issue by mariusrugan** [hypriot/cluster-lab#24]
Hi, 

on a rPI Model B Revision 2.0, 512MB RAM,
using http://downloads.hypriot.com/hypriot_20160121-235123_clusterlab.img.zip
i had to modify the start script in order for the system to pickup on master. 

(otherwise 192.168.200.1 was always assigned on node-1, so i had to debug avahi-browse output and it only 'refreshes' when the daemon is restarted)

```bash
echo -e "#-----------------\n# check if leader\n#-----------------"

setip 192.168.200.254
sleep 5
systemctl restart avahi-daemon.service
sleep 5

CLUSTERMASTERIP=$(avahi-browse _cluster._tcp -t -r -p | grep 'os-release=hypriot' | grep '^=' | grep ';Cluster-Master' |  grep 'eth0\.' | grep IPv4 | awk -F ';' 'BEGIN { format="%s\n" }{ printf(format,$8) }')
```

is this something worth a change (by me via PR-ing) or you have other plans related to this ?

**Comment by firecyberice** [comment]
Hi have a look here https://github.com/hypriot/cluster-lab/tree/refactor-cluster-lab we are currently rewriting the cluster-lab code. Maybe you can try this new version.
I close this issue for now but feel free to reopen it.
