### ISSUE TITLE
Investigate if we could use Swarm Replicas to make the Cluster Lab more resilient

### ISSUE THREAD

**Issue by Govinda-Fichtner** [hypriot/cluster-lab#3]
See [High Availability in Docker Swarm](https://docs.docker.com/swarm/multi-manager-setup/) for possible solutions on how to do that.

Having more than one Swarm Manager would make the Cluster Lab more resilient in the event that the master node goes down.

**Comment by firecyberice** [comment]
Not without fixing that the DHCP server is ONLY running on the first node too.

**Comment by Govinda-Fichtner** [comment]
In the newly refactored Cluster Lab we do use the `--replication` flag and start a Swarm Manage container on every cluster node

https://github.com/hypriot/cluster-lab/blob/master/package/usr/local/lib/cluster-lab/container_lib#L145

That's why would consider this issue closed.
