### ISSUE TITLE
Allow docker swarm token to work

### ISSUE THREAD

**Issue by richtong** [hypriot/cluster-lab#33]
We are finding that consul for large networks is unstable. Members do not join properly for instance. For more flexibility, it would be great to allow the use of hosted swarm that use the token:// with a unique token address rather than consul. This means that the system needs to come up with a slightly modified token. And you should get the token from the user or by running `docker run swarm create` which will give you a guid. I haven't tried it bu `docker run hypriot/rpi-swarm create` should do the same.

The specific change is to modify the cluster-lab.conf so that there is a DOCKER_CONSUL_CONF for consul and a DOCKER_SWARM_CONF for non-consul. Then the cluster-lab script needs to be able to switch. Perhaps add a new command to cluster-lab script. There are bunch of different approaches but the core line that needs to change is assuming $TOKEN has the unique id

```
DOCKER_OPTS='{\\n \
  \"storage-driver\": \"overlay\", \\n \
  \"hosts\": [\"fd://\", \"tcp://${CLUSTER_NODE_IP}:2375\"], \\n \
  \"cluster-advertise\": \"${CLUSTER_NODE_IP}:2375\", \\n \
  \"cluster-store\": \"consul://${CLUSTER_NODE_IP}:8500\", \\n \
  \"label\": [\"hypriot.arch=${ARCHITECTURE}\",\"hypriot.hierarchy=${CLUSTER_NODE_ROLE}\"] \\n \
}'
```

For the slaves you need to be smart about what swarm image you execute depending on Intel vs arm roughly (as I have not yet figured out all the escapes needed):

```
DOCKER_OPTS='{\\n \
  \"storage-driver\": \"overlay\", \\n \
  \"swarm\"  \\n \
  \"swarm-image\": \"hypriot/rpi-swarm", \\n \  
  \"swarm-advertise\": \"${CLUSTER_TOKEN}", \\n \
  \"label\": [\"hypriot.arch=${ARCHITECTURE}\",\"hypriot.hierarchy=${CLUSTER_NODE_ROLE}\"] \\n \
}'
```

For the master you need all of the above plus

```
  \"swarmmaster\": \"overlay\", \\n \
```

**Comment by firecyberice** [comment]
Consul is not only used for swarm but also for docker overlay networks. These networks need a key-value store like consul. How do you manage them in your case with the swarm token?

**Comment by richtong** [comment]
I would say we do not use overlay when using swarm. Right now for our 40 nodes, we do not use overlays. I was not sure when consul didn't attach whether it was overlays or consul itself that was failing. We have since upgrade to a better (small business vs unmanaged) switch so need to try again, but since swarm doesn't do overlays I'd say we set vlan off when we do swarm.

**Comment by firecyberice** [comment]
Our DOCKER_OPTS are official docker daemon options where do you find the corresponding flags like `swarm-image` `swarm-advertise` etc?
For being  smart enough to select the correct images for each supported arch we have https://github.com/hypriot/cluster-lab/blob/master/package/usr/local/bin/cluster-lab#L15-28.
