### ISSUE TITLE
Move config from daemon.json to docker.service

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/cluster-lab#36]
To make cluster-lab compatible to our lastest image-builder-rpi v0.5.17 which is now compatible with docker-machine we also have to move the config from daemon.json back to docker.service.

**Comment by nsteinmetz** [comment]
Hi,

For the one who were on the version using the json file, you should have added a remove ``/etc/docker/daemon.json`` otherwise it prevents docker to start. Seems removing the file is enough.

Nicolas
