### ISSUE TITLE
Set Network config (IP Address, Netmarsk, Gateway) and DNS

### ISSUE THREAD

**Issue by nsteinmetz** [hypriot/cluster-lab#5]
Hi,

I plan to use CL in a DMZ context where I have no DHCP by default nor DNS ; so I don't know if the issue should be reported there or in hypriot/flash. Let me know which one is the best.

At the end, what I would like is something like:
* `` --ipaddress`` for the IP of the node with a /24 or something ; ex: ``--ipaddress=192.168.8.100/24`` ; a variant could be ``--ipaddress`` and ``--netmask`` depending on the expected format
* ``--gateway`` : for the IP of my gateway to internet : ex ``--gateway=192.168.8.1``
* ``--dns``: to set the DNS with at least one, but ideally a list of dns like ``--dns="8.8.8.8 8.8.4.4"``

It would lead to:

```
flash --hostname cl-master -ipaddress=192.168.8.100/24 --gateway=192.168.8.1 --dns="8.8.8.8 8.8.4.4" http://downloads.hypriot.com/hypriot-rpi-20151128-152209-docker-swarm-cluster.img.zip
```

Would it make sense ?

**Comment by firecyberice** [comment]
As a workaround you can add your network setting manually to /etc/network/interfaces before booting the SD.

You can also open a PR in the hypriot/flash repo.

**Comment by nsteinmetz** [comment]
Hi,

How can I do this ? Once the img is done on sdcard, I only see a few .dtb, .elf, .datn .txt files ?

**Comment by luxas** [comment]
If you're on windows, I don't know, but otherwise, try this
```
lsblk

# Find the sd card e.g. /dev/sdb

mkdir /tmp/mysdcard
mount /dev/sdb2 /tmp/mysdcard
cd /tmp/mysdcard/etc/network/interfaces
... do things ...
umount  /tmp/mysdcard
```

**Comment by nsteinmetz** [comment]
Hi,

I'm on archlinux.

What I did and what basically the flash utility does:

```
sudo dd if=hypriot-rpi-20151128-152209-docker-swarm-cluster.img of=/dev/mmcblk0 bs=1M
```

When I mount my flash drive, I have (result of ``tree`` command):

```
├── bcm2708-rpi-b.dtb
├── bcm2708-rpi-b-plus.dtb
├── bcm2708-rpi-cm.dtb
├── bcm2709-rpi-2-b.dtb
├── bootcode.bin
├── cmdline.txt
├── config.txt
├── COPYING.linux
├── fixup_cd.dat
├── fixup.dat
├── fixup_db.dat
├── fixup_x.dat
├── kernel7.img
├── kernel.img
├── LICENCE.broadcom
├── occidentalis.txt
├── overlays
│   ├── ads7846-overlay.dtb
│   ├── bmp085_i2c-sensor-overlay.dtb
│   ├── dht11-overlay.dtb
│   ├── enc28j60-overlay.dtb
│   ├── gpio-poweroff-overlay.dtb
│   ├── hifiberry-amp-overlay.dtb
│   ├── hifiberry-dac-overlay.dtb
│   ├── hifiberry-dacplus-overlay.dtb
│   ├── hifiberry-digi-overlay.dtb
│   ├── hy28a-overlay.dtb
│   ├── hy28b-overlay.dtb
│   ├── i2c-rtc-overlay.dtb
│   ├── i2s-mmap-overlay.dtb
│   ├── iqaudio-dac-overlay.dtb
│   ├── iqaudio-dacplus-overlay.dtb
│   ├── lirc-rpi-overlay.dtb
│   ├── mcp2515-can0-overlay.dtb
│   ├── mcp2515-can1-overlay.dtb
│   ├── mmc-overlay.dtb
│   ├── mz61581-overlay.dtb
│   ├── piscreen-overlay.dtb
│   ├── pitft28-resistive-overlay.dtb
│   ├── pps-gpio-overlay.dtb
│   ├── pwm-2chan-overlay.dtb
│   ├── pwm-overlay.dtb
│   ├── raspidac3-overlay.dtb
│   ├── README
│   ├── rpi-dac-overlay.dtb
│   ├── rpi-display-overlay.dtb
│   ├── rpi-ft5406-overlay.dtb
│   ├── rpi-proto-overlay.dtb
│   ├── rpi-sense-overlay.dtb
│   ├── sdhost-overlay.dtb
│   ├── sdio-overlay.dtb
│   ├── smi-dev-overlay.dtb
│   ├── smi-nand-overlay.dtb
│   ├── smi-overlay.dtb
│   ├── spi-bcm2708-overlay.dtb
│   ├── spi-bcm2835-overlay.dtb
│   ├── spi-dma-overlay.dtb
│   ├── tinylcd35-overlay.dtb
│   ├── uart1-overlay.dtb
│   ├── vga666-overlay.dtb
│   ├── w1-gpio-overlay.dtb
│   └── w1-gpio-pullup-overlay.dtb
├── start_cd.elf
├── start_db.elf
├── start.elf
└── start_x.elf

1 directory, 65 files
```

So I think so far that after 1st run, system is properly expanded on flash drive but so far I can't hack ``/etc/network/interfaces`` at this stage.

Am I correct or did I miss something ? Otherwise, I wouldn't have asked such a question ;-)

**Comment by DieterReuter** [comment]
@nsteinmetz the sd card is formatted with 2 partitions on it. 1st one is a fat/fat32 and this is exactly what your listed. The 2nd partition is ext3 and contains the linux filesystem. So you have to mount the 2nd partition to see the linux file system. Just run a `sudo disk -l /dev/mmcblk0` to check the partition table.

**Comment by nsteinmetz** [comment]
Argh indeed,. I don't know why the 2nd partition wasn't showing up. It was well listed via ``fdisk -l`` but ``/dev/mmcblk0p2`` did not exist until I ejected and inserted backmy flash drive.

Now I can see & adjust content in the 2nd partition !

Thanks @DieterReuter !

**Comment by aetherical** [comment]
On 2015-12-28 08:30, Nicolas Steinmetz wrote:
> Argh indeed,. I don't know why the 2nd partition wasn't showing up. It
> was well listed via fdisk -l but /dev/mmcblk0p2 did not exist until I
> ejected and inserted backmy flash drive.
> 
> Now I can see & adjust content in the 2nd partition !
> 
> Thanks @DieterReuter [1] !
> 
> --
> Reply to this email directly or view it on GitHub [2].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/DieterReuter
> [2] 
> https://github.com/hypriot/cluster-lab/issues/5#issuecomment-167568685


I noticed last week a "feature" of the flash script on linux:  when 
flashing a new sd card it isn't re-reading the card to pick up the new 
partitions; it just gets the fat32 one. This isn't an issue when it's 
already written.

I've not had a chance to look at it in depth, however I should sometime 
this week...
