### ISSUE TITLE
Example for docker vagrant provider ?

### ISSUE THREAD

**Issue by bcopy** [hypriot/cluster-lab#54]
Hello,

The cluster lab main example shows using Vagrant with Virtualbox as an example. I'm on a headless CentOS 7 system with only docker available.

I've been able to run a vagrant + docker example such as : https://github.com/bubenkoff/vagrant-docker-example

But when I try to add "--provider docker" to the first vagrant instruction, I get :

```
[root@test-vm vagrant]# /usr/bin/vagrant up --provider=docker
No usable default provider could be found for your system.
```

Or maybe using a docker provider for cluster-lab is not possible ?

**Comment by firecyberice** [comment]
You cannot use docker as provider for this. This Vagrantfile is used to demonstrate how docker swarm works without setting up bare metal or hosted machines.
