### ISSUE TITLE
firstboot_done : command not found

### ISSUE THREAD

**Issue by nsteinmetz** [hypriot/cluster-lab#6]
Hi,

Starting from basic hypriot os image (latest one), I then installed ``cluster-lab`` package and when I do ``systemctl start cluster-start``, at the end, I have:

```
firstboot_done: command not found
```
So I hope, it was just a useless text that I missed.

At least, consul UI is up and running.

Brw, on home page project on github, package is ``cluster-lab``and not ``hypriot-cluster-lab``.

**Comment by firecyberice** [comment]
I fixed the name of the package it should be `hypriot-cluster-lab`

I don't currently know there the `firstboot_done: command not found`
message is created but the `firstboot_done` is a marker that the partition is already expanded.
