### ISSUE TITLE
UI container can't find ./dockerui

### ISSUE THREAD

**Issue by joshuacox** [hypriot/cluster-lab#7]
Anyone else having trouble starting the UI container?

```
docker -H MASTER_IP:2378 run --cidfile=dockeruipull -d -p 9000:9000 --env="constraint:node==hypriot11" --name dockerui1 hypriot/rpi-dockerui -e http://MASTER_IP:2378
7496213a97ad621da51d809dc16c6e6d4574a5958fc48355aff36b71d0efca15
Error response from daemon: Cannot start container 7496213a97ad621da51d809dc16c6e6d4574a5958fc48355aff36b71d0efca15: [8] System error: exec: "./dockerui": stat ./dockerui: no such file or directory
```

**Comment by nsteinmetz** [comment]
Yes, I reported the same issue yesterday on hypriot/rpi-dockerui project: https://github.com/hypriot/rpi-dockerui/issues/3

**Comment by firecyberice** [comment]
This  should be fixed by  hypriot/rpi-dockerui#3

**Comment by nsteinmetz** [comment]
Thanks,

Don't forget to push a new image to Docker Hub so that we can fetch it ; it's still the old one ;-)

**Comment by firecyberice** [comment]
Yes our Ci has some trouble. We just switched from drone 0.3.0 to drone 0.4.0 ...

**Comment by firecyberice** [comment]
As workaround you can add `--entrypoint /dockerui` to the `docker run` command.

**Comment by firecyberice** [comment]
@nsteinmetz  pushed to the hub ;-)
